#!/bin/bash

THIS_SCRIPT_DIR=$( dirname $( realpath $0 ) )
REAL_BIN_DIR=$( realpath "$THIS_SCRIPT_DIR/../bin" )

THIS_SCRIPT_NAME=$( basename $0 )
BYOND_EXEC="$REAL_BIN_DIR/byondexec"

BYOND_PROGRAM_TO_EXEC="$REAL_BIN_DIR/$THIS_SCRIPT_NAME"

shift 1

# We use `bash` here, as `byondexec` (despite being marked `#!/bin/sh`) attempts to use `[[` - which
# is special syntax not available to `sh`.
bash "$BYOND_EXEC" "$BYOND_PROGRAM_TO_EXEC" "$@"
